# Generated by Django 5.0.1 on 2024-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.AddField(
            model_name='ad',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
